import type { ScoreRule } from "@/lib/decision/rules/types";

/** Reglas determinísticas — sin IA. */
export const SCORE_RULES: ScoreRule[] = [
  {
    id: "disnea-b-lines-core",
    when: { symptoms: ["disnea"], findings: ["b-lines"] },
    add: { eap: 4, sobrecarga: 4, ards: 3, neumonia: 3 },
    dontMiss: ["tep", "neumotorax"],
    nextStudy: "Completar BLUE en campos anteriores, laterales y posteriores; correlacionar con BNP/ECG.",
  },
  {
    id: "disnea-b-lines-ventilado",
    when: { symptoms: ["disnea"], findings: ["b-lines"], contexts: ["ventilado"] },
    add: { ards: 3, neumonia: 2 },
    dontMiss: ["tep"],
    nextStudy: "Valorar driving pressure, compliance y consolidación dependiente.",
  },
  {
    id: "disnea-b-lines-agudo",
    when: { symptoms: ["disnea"], findings: ["b-lines"], contexts: ["agudo"] },
    add: { eap: 2, tep: 2 },
    nextStudy: "Descartar TEP si inestabilidad o factores de riesgo; considerar ecocardiograma.",
  },
  {
    id: "disnea-consolidacion",
    when: { symptoms: ["disnea"], findings: ["consolidacion"] },
    add: { neumonia: 5, ards: 2, sobrecarga: 1 },
    dontMiss: ["tep", "neumotorax"],
    nextStudy: "PLAPS / campos posteriores; antibiótico empírico según contexto.",
  },
  {
    id: "disnea-a-lines",
    when: { symptoms: ["disnea"], findings: ["a-lines"] },
    add: { "asma-epoc": 4, tep: 3 },
    dontMiss: ["tep", "neumotorax"],
    nextStudy: "Modo M pleural; si sospecha TEP, protocolo DVT/TEP según guía local.",
  },
  {
    id: "disnea-pleural-effusion",
    when: { symptoms: ["disnea"], findings: ["pleural-effusion"] },
    add: { "derrame-pleural": 5, sobrecarga: 3, neumonia: 2 },
    dontMiss: ["tep"],
    nextStudy: "Cuantificar derrame; considerar toracocentesis diagnóstica si inestable.",
  },
  {
    id: "disnea-lung-point",
    when: { symptoms: ["disnea"], findings: ["lung-point"] },
    add: { neumotorax: 6 },
    dontMiss: ["neumotorax", "tep"],
    nextStudy: "Confirmar neumotórax; preparar descompresión si tensión.",
  },
  {
    id: "hipoxemia-b-lines",
    when: { symptoms: ["hipoxemia"], findings: ["b-lines"] },
    add: { eap: 4, ards: 3, sobrecarga: 3, neumonia: 2 },
    dontMiss: ["tep", "neumotorax"],
    nextStudy: "Perfil BLUE completo + gasometría; reevaluar tras fluidos/diurético.",
  },
  {
    id: "hipoxemia-consolidacion",
    when: { symptoms: ["hipoxemia"], findings: ["consolidacion"] },
    add: { neumonia: 5, ards: 3 },
    dontMiss: ["tep"],
    nextStudy: "PLAPS y campos posteriores; correlacionar con infiltrado radiológico.",
  },
  {
    id: "choque-ivc-collapsed",
    when: { symptoms: ["choque"], findings: ["ivc-collapsed"] },
    add: { "shock-hipovolemico": 6, tep: 2 },
    dontMiss: ["shock-hipovolemico", "tamponamiento"],
    nextStudy: "RUSH: pericardio, VI, VCI, líquido libre; prueba de fluidos si indicado.",
  },
  {
    id: "choque-ivc-plethoric",
    when: { symptoms: ["choque"], findings: ["ivc-plethoric"] },
    add: { "shock-cardiogenico": 4, sobrecarga: 4, "shock-distributivo": 2 },
    dontMiss: ["tamponamiento", "tep"],
    nextStudy: "Eco cardíaca + VExUS; valorar inotrópico vs fluidos.",
  },
  {
    id: "choque-pericardial",
    when: { symptoms: ["choque"], findings: ["pericardial-effusion"] },
    add: { tamponamiento: 6, "shock-cardiogenico": 3 },
    dontMiss: ["tamponamiento"],
    nextStudy: "Subxifoideo y apical; preparar pericardiocentesis si inestable.",
  },
  {
    id: "choque-free-fluid",
    when: { symptoms: ["choque"], findings: ["free-fluid"] },
    add: { "shock-hipovolemico": 5, "abdomen-agudo": 3 },
    dontMiss: ["shock-hipovolemico", "tamponamiento"],
    nextStudy: "eFAST completo + pelvis; control hemodinámico estrecho.",
  },
  {
    id: "trauma-pneumothorax",
    when: { symptoms: ["trauma"], findings: ["pneumothorax"] },
    add: { neumotorax: 6, hemotorax: 3 },
    dontMiss: ["neumotorax", "tamponamiento"],
    nextStudy: "eFAST + líneas pleurales bilaterales; descompresión si tensión.",
  },
  {
    id: "trauma-free-fluid",
    when: { symptoms: ["trauma"], findings: ["free-fluid"] },
    add: { "shock-hipovolemico": 5, "abdomen-agudo": 4 },
    dontMiss: ["shock-hipovolemico", "tamponamiento"],
    nextStudy: "eFAST seriado; activar cirugía si inestabilidad persistente.",
  },
  {
    id: "oliguria-portal-pulsatile",
    when: { symptoms: ["oliguria"], findings: ["portal-pulsatile"] },
    add: { "congestion-venosa": 6, "aki-cardiorenal": 4, sobrecarga: 3 },
    dontMiss: ["shock-hipovolemico"],
    nextStudy: "VExUS completo (VCI, hepática, porta, renal); restricción hídrica/diurético.",
  },
  {
    id: "oliguria-ivc-collapsed",
    when: { symptoms: ["oliguria"], findings: ["ivc-collapsed"] },
    add: { "aki-prerrenal": 5, "shock-hipovolemico": 4 },
    dontMiss: ["tamponamiento"],
    nextStudy: "RUSH + respuesta a cristaloide; monitorizar diuresis horaria.",
  },
  {
    id: "context-septico",
    when: { contexts: ["septico"] },
    add: { "shock-distributivo": 3, neumonia: 2 },
    dontMiss: ["shock-hipovolemico"],
    nextStudy: "Foco infeccioso + lactato; antibiótico precoz según protocolo sépsis.",
  },
  {
    id: "context-postop",
    when: { contexts: ["postop"] },
    add: { ards: 2, "aki-prerrenal": 2, "shock-hipovolemico": 2 },
    nextStudy: "Balance hídrico y dolor; descartar íleo / sangrado oculto.",
  },
  {
    id: "symptom-disnea-fallback",
    when: { symptoms: ["disnea"] },
    add: { tep: 1, neumonia: 1, eap: 1 },
    dontMiss: ["tep", "neumotorax"],
    nextStudy: "Protocolo BLUE sistemático según queja dominante.",
  },
  {
    id: "symptom-choque-fallback",
    when: { symptoms: ["choque"] },
    add: { "shock-hipovolemico": 2, "shock-cardiogenico": 2, tamponamiento: 2 },
    dontMiss: ["tamponamiento", "shock-hipovolemico"],
    nextStudy: "RUSH en <5 min; repetir post-intervención.",
  },
  {
    id: "symptom-hipoxemia-fallback",
    when: { symptoms: ["hipoxemia"] },
    add: { neumonia: 2, ards: 2, tep: 1 },
    dontMiss: ["tep"],
    nextStudy: "BLUE + gasometría; optimizar PEEP/FiO2 si ventilado.",
  },
  {
    id: "symptom-trauma-fallback",
    when: { symptoms: ["trauma"] },
    add: { "shock-hipovolemico": 2, neumotorax: 2, hemotorax: 1 },
    dontMiss: ["neumotorax", "tamponamiento"],
    nextStudy: "eFAST extendido; control seriado en sala.",
  },
  {
    id: "symptom-oliguria-fallback",
    when: { symptoms: ["oliguria"] },
    add: { "aki-prerrenal": 2, "congestion-venosa": 2 },
    dontMiss: ["shock-hipovolemico"],
    nextStudy: "VExUS + RUSH; revisar fármacos nefrotóxicos y volumen.",
  },
];
