import type { AdaptiveCaseGraph, CaseBranch, CaseOutcome, DecisionNode } from "@/lib/cases/types";

const nodes: Record<string, DecisionNode> = {
  presentation: {
    id: "presentation",
    kind: "presentation",
    title: "Paciente",
    difficulty: "basico",
    prompt: "Revisa el escenario. El flujo se adaptará a tus decisiones.",
    choices: [
      {
        id: "ready",
        label: "Continuar al protocolo",
        isOptimal: true,
        feedback: "Prioriza estabilización y un protocolo pulmonar dirigido.",
      },
    ],
  },
  protocol: {
    id: "protocol",
    kind: "protocol",
    title: "Elegir protocolo",
    difficulty: "basico",
    prompt: "¿Qué protocolo POCUS inicias primero?",
    choices: [
      {
        id: "blue",
        label: "BLUE básico",
        isOptimal: true,
        feedback: "Correcto para disnea aguda con crepitantes.",
        resource: { protocolSlug: "blue", protocolStepId: "pattern" },
      },
      {
        id: "fast",
        label: "FAST / eFAST",
        isOptimal: false,
        feedback: "No es el primer paso sin sospecha de trauma o líquido libre.",
        resource: { protocolSlug: "fast", protocolStepId: "ruq" },
      },
      {
        id: "rush",
        label: "RUSH",
        isOptimal: false,
        feedback: "RUSH es para shock; aquí prima la ventilación.",
        resource: { protocolSlug: "rush", protocolStepId: "heart" },
      },
      {
        id: "vexus",
        label: "VExUS",
        isOptimal: false,
        feedback: "Complementa tras BLUE si hay sospecha de congestión.",
        resource: { protocolSlug: "vexus", protocolStepId: "ivc" },
      },
    ],
  },
  "window-correct": {
    id: "window-correct",
    kind: "window",
    title: "Elegir ventana",
    difficulty: "basico",
    prompt: "Ruta BLUE — ¿qué ventana exploras primero?",
    choices: [
      {
        id: "blue-anterior",
        label: "BLUE anterior bilateral",
        isOptimal: true,
        feedback: "Núcleo del protocolo: perfil A/B y sliding.",
        resource: { protocolSlug: "blue", protocolStepId: "sliding", atlasModule: "lung" },
      },
      {
        id: "plaps-only",
        label: "Solo PLAPS",
        isOptimal: false,
        feedback: "PLAPS complementa; no sustituye el anterior.",
        resource: { protocolSlug: "blue", protocolStepId: "plaps" },
      },
      {
        id: "costophrenic",
        label: "Solo costofrénico",
        isOptimal: false,
        feedback: "Falta valorar intersticio y sliding anterior.",
        resource: { atlasModule: "lung", mediaId: "lung-pleural-effusion" },
      },
      {
        id: "subxiphoid",
        label: "Subxifoideo",
        isOptimal: false,
        feedback: "Eco cardíaca después de caracterizar el pulmón.",
        resource: { protocolSlug: "blue", protocolStepId: "pattern" },
      },
    ],
  },
  "window-recovery": {
    id: "window-recovery",
    kind: "window",
    title: "Recuperar ventana",
    difficulty: "intermedio",
    prompt: "Elegiste un protocolo menos dirigido. ¿Cómo corriges el enfoque pulmonar?",
    choices: [
      {
        id: "blue-anterior",
        label: "BLUE anterior bilateral",
        isOptimal: true,
        feedback: "Recuperas el eje correcto del caso.",
        resource: { protocolSlug: "blue", protocolStepId: "sliding", atlasModule: "lung" },
      },
      {
        id: "plaps-only",
        label: "Solo PLAPS",
        isOptimal: false,
        feedback: "Sigue incompleto para disnea aguda.",
        resource: { protocolSlug: "blue", protocolStepId: "plaps" },
      },
      {
        id: "costophrenic",
        label: "Solo costofrénico",
        isOptimal: false,
        feedback: "No explica crepitantes bilaterales.",
        resource: { atlasModule: "lung", mediaId: "lung-pleural-effusion" },
      },
      {
        id: "subxiphoid",
        label: "Subxifoideo",
        isOptimal: false,
        feedback: "Prioriza campos anteriores en BLUE.",
        resource: { protocolSlug: "blue", protocolStepId: "pattern" },
      },
    ],
  },
  "finding-correct": {
    id: "finding-correct",
    kind: "finding",
    title: "Elegir hallazgo",
    difficulty: "basico",
    prompt: "Cometas verticales bilaterales hasta la pleura. ¿Qué reportas?",
    choices: [
      {
        id: "b-lines",
        label: "Líneas B bilaterales",
        isOptimal: true,
        feedback: "Perfil B — edema intersticial/alveolar.",
        resource: { mediaId: "lung-b-lines", atlasModule: "lung" },
      },
      {
        id: "a-lines",
        label: "Patrón A dominante",
        isOptimal: false,
        feedback: "No encaja con crepitantes e hipoxemia.",
        resource: { mediaId: "lung-a-lines", atlasModule: "lung" },
      },
      {
        id: "consolidation",
        label: "Consolidación",
        isOptimal: false,
        feedback: "Sin fiebre ni foco único posterior.",
        resource: { mediaId: "lung-consolidation", atlasModule: "lung" },
      },
      {
        id: "lung-point",
        label: "Lung point",
        isOptimal: false,
        feedback: "Requiere sliding ausente.",
        resource: { mediaId: "lung-lung-point", atlasModule: "lung" },
      },
    ],
  },
  "finding-misread": {
    id: "finding-misread",
    kind: "finding",
    title: "Reinterpretar hallazgo",
    difficulty: "intermedio",
    prompt: "Ventana incompleta. Aún hay crepitantes bilaterales — ¿qué predominio?",
    choices: [
      {
        id: "b-lines",
        label: "Líneas B bilaterales",
        isOptimal: true,
        feedback: "Recuperas el hallazgo clave.",
        resource: { mediaId: "lung-b-lines", atlasModule: "lung" },
      },
      {
        id: "a-lines",
        label: "Patrón A",
        isOptimal: false,
        feedback: "Poco probable en este cuadro.",
        resource: { mediaId: "lung-a-lines", atlasModule: "lung" },
      },
      {
        id: "consolidation",
        label: "Consolidación",
        isOptimal: false,
        feedback: "Orienta a neumonía; no es el patrón principal.",
        resource: { mediaId: "lung-consolidation", atlasModule: "lung" },
      },
      {
        id: "lung-point",
        label: "Lung point",
        isOptimal: false,
        feedback: "No hay datos de neumotórax.",
        resource: { mediaId: "lung-lung-point", atlasModule: "lung" },
      },
    ],
  },
  "finding-offtrack": {
    id: "finding-offtrack",
    kind: "finding",
    title: "Hallazgo (ruta alterna)",
    difficulty: "intermedio",
    prompt: "Sin BLUE completo: ¿qué concluyes con la información limitada?",
    choices: [
      {
        id: "b-lines",
        label: "Líneas B",
        isOptimal: true,
        feedback: "Aún puedes orientar a EAP si lo confirmas.",
        resource: { mediaId: "lung-b-lines", atlasModule: "lung" },
      },
      {
        id: "consolidation",
        label: "Consolidación / neumonía",
        isOptimal: false,
        feedback: "Sesgo por protocolo inadecuado; sin fiebre.",
        resource: { mediaId: "lung-consolidation", atlasModule: "lung" },
      },
      {
        id: "a-lines",
        label: "Patrón A",
        isOptimal: false,
        feedback: "No explica la clínica.",
        resource: { mediaId: "lung-a-lines", atlasModule: "lung" },
      },
      {
        id: "lung-point",
        label: "Lung point",
        isOptimal: false,
        feedback: "Sin sliding ausente no aplica.",
        resource: { mediaId: "lung-lung-point", atlasModule: "lung" },
      },
    ],
  },
  "conduct-optimal": {
    id: "conduct-optimal",
    kind: "conduct",
    title: "Elegir conducta",
    difficulty: "basico",
    prompt: "Perfil B e hipoxemia — conducta inicial:",
    choices: [
      {
        id: "vmni-diuretic",
        label: "VMNI + furosemida IV",
        isOptimal: true,
        feedback: "Primera línea en EAP cardiogénico.",
      },
      {
        id: "intubate",
        label: "IOT inmediata",
        isOptimal: false,
        feedback: "Si falla VMNI o hay alteración neurológica.",
      },
      {
        id: "antibiotics",
        label: "Antibióticos IV",
        isOptimal: false,
        feedback: "Sin foco infeccioso claro.",
      },
      {
        id: "fluids",
        label: "Bolo de cristaloide",
        isOptimal: false,
        feedback: "Empeora el edema pulmonar.",
      },
    ],
  },
  "conduct-suboptimal": {
    id: "conduct-suboptimal",
    kind: "conduct",
    title: "Conducta tras error",
    difficulty: "intermedio",
    prompt: "Hallazgo parcialmente acertado — ¿qué haces ahora?",
    choices: [
      {
        id: "vmni-diuretic",
        label: "VMNI + furosemida IV",
        isOptimal: true,
        feedback: "Aún es la conducta más segura si hay perfil B.",
      },
      {
        id: "intubate",
        label: "IOT inmediata",
        isOptimal: false,
        feedback: "Reservar para falla de VMNI.",
      },
      {
        id: "antibiotics",
        label: "Antibióticos IV",
        isOptimal: false,
        feedback: "No es la prioridad sin foco infeccioso.",
      },
      {
        id: "fluids",
        label: "Bolo de cristaloide",
        isOptimal: false,
        feedback: "Riesgo de empeorar congestión.",
      },
    ],
  },
};

const outcomes: Record<string, CaseOutcome> = {
  "outcome-optimal": {
    id: "outcome-optimal",
    title: "EAP — manejo acertado",
    explanation: "Ruta BLUE completa con perfil B y VMNI. Integración clínica correcta.",
    teachingPoint: "Disnea aguda + líneas B bilaterales: pensar EAP y tratar antes de antibióticos.",
    pathType: "optimal",
    resources: {
      protocolSlug: "blue",
      protocolStepId: "pattern",
      mediaId: "lung-b-lines",
      atlasModule: "lung",
    },
  },
  "outcome-partial": {
    id: "outcome-partial",
    title: "EAP probable — ruta parcial",
    explanation: "Llegaste al diagnóstico pero con desvíos. Revisa ventana y conducta.",
    teachingPoint: "Un error de protocolo o ventana puede retrasar VMNI.",
    pathType: "partial",
    resources: {
      protocolSlug: "blue",
      protocolStepId: "pattern",
      mediaId: "lung-b-lines",
      atlasModule: "lung",
    },
  },
  "outcome-pneumonia": {
    id: "outcome-pneumonia",
    title: "Sesgo a neumonía",
    explanation: "Consolidación sin contexto infeccioso ni BLUE completo — riesgo de sobretratamiento.",
    teachingPoint: "No saltar a antibióticos sin perfil B y clínica compatible.",
    pathType: "incorrect",
    resources: { protocolSlug: "blue", protocolStepId: "plaps", atlasModule: "lung" },
  },
  "outcome-incorrect": {
    id: "outcome-incorrect",
    title: "Manejo inadecuado",
    explanation: "La combinación de decisiones no protege al paciente con EAP.",
    teachingPoint: "Repasa BLUE: sliding, perfil A/B, luego conducta.",
    pathType: "incorrect",
    resources: { protocolSlug: "blue", protocolStepId: "sliding", atlasModule: "lung" },
  },
  "outcome-harm": {
    id: "outcome-harm",
    title: "Conducta dañina",
    explanation: "Volumen o IOT precoz sin indicación empeoran el desenlace en EAP.",
    teachingPoint: "VMNI + diurético es primera línea si no hay contraindicación.",
    pathType: "incorrect",
    resources: { protocolSlug: "blue", protocolStepId: "pattern", atlasModule: "lung" },
  },
};

const branches: CaseBranch[] = [
  { fromNodeId: "presentation", choiceId: "ready", nextNodeId: "protocol" },

  { fromNodeId: "protocol", choiceId: "blue", nextNodeId: "window-correct" },
  { fromNodeId: "protocol", choiceId: "fast", nextNodeId: "window-recovery" },
  { fromNodeId: "protocol", choiceId: "rush", nextNodeId: "finding-offtrack" },
  { fromNodeId: "protocol", choiceId: "vexus", nextNodeId: "window-recovery" },

  { fromNodeId: "window-correct", choiceId: "blue-anterior", nextNodeId: "finding-correct" },
  { fromNodeId: "window-correct", choiceId: "plaps-only", nextNodeId: "finding-misread" },
  { fromNodeId: "window-correct", choiceId: "costophrenic", nextNodeId: "finding-misread" },
  { fromNodeId: "window-correct", choiceId: "subxiphoid", nextNodeId: "finding-misread" },

  { fromNodeId: "window-recovery", choiceId: "blue-anterior", nextNodeId: "finding-correct" },
  { fromNodeId: "window-recovery", choiceId: "plaps-only", nextNodeId: "finding-offtrack" },
  { fromNodeId: "window-recovery", choiceId: "costophrenic", nextNodeId: "finding-offtrack" },
  { fromNodeId: "window-recovery", choiceId: "subxiphoid", nextNodeId: "finding-offtrack" },

  { fromNodeId: "finding-correct", choiceId: "b-lines", nextNodeId: "conduct-optimal" },
  { fromNodeId: "finding-correct", choiceId: "a-lines", nextNodeId: "conduct-suboptimal" },
  { fromNodeId: "finding-correct", choiceId: "consolidation", nextNodeId: "conduct-suboptimal" },
  { fromNodeId: "finding-correct", choiceId: "lung-point", nextNodeId: "conduct-suboptimal" },

  { fromNodeId: "finding-misread", choiceId: "b-lines", nextNodeId: "conduct-optimal" },
  { fromNodeId: "finding-misread", choiceId: "a-lines", outcomeId: "outcome-partial" },
  { fromNodeId: "finding-misread", choiceId: "consolidation", outcomeId: "outcome-pneumonia" },
  { fromNodeId: "finding-misread", choiceId: "lung-point", outcomeId: "outcome-incorrect" },

  { fromNodeId: "finding-offtrack", choiceId: "b-lines", nextNodeId: "conduct-suboptimal" },
  { fromNodeId: "finding-offtrack", choiceId: "consolidation", outcomeId: "outcome-pneumonia" },
  { fromNodeId: "finding-offtrack", choiceId: "a-lines", outcomeId: "outcome-incorrect" },
  { fromNodeId: "finding-offtrack", choiceId: "lung-point", outcomeId: "outcome-incorrect" },

  { fromNodeId: "conduct-optimal", choiceId: "vmni-diuretic", outcomeId: "outcome-optimal" },
  { fromNodeId: "conduct-optimal", choiceId: "intubate", outcomeId: "outcome-partial" },
  { fromNodeId: "conduct-optimal", choiceId: "antibiotics", outcomeId: "outcome-partial" },
  { fromNodeId: "conduct-optimal", choiceId: "fluids", outcomeId: "outcome-harm" },

  { fromNodeId: "conduct-suboptimal", choiceId: "vmni-diuretic", outcomeId: "outcome-partial" },
  { fromNodeId: "conduct-suboptimal", choiceId: "intubate", outcomeId: "outcome-partial" },
  { fromNodeId: "conduct-suboptimal", choiceId: "antibiotics", outcomeId: "outcome-pneumonia" },
  { fromNodeId: "conduct-suboptimal", choiceId: "fluids", outcomeId: "outcome-harm" },
];

export const disneaAgudaGraph: AdaptiveCaseGraph = {
  startNodeId: "presentation",
  nodes,
  outcomes,
  branches,
};
